name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore NutrishaAI.API/NutrishaAI.API.csproj

    - name: Build
      run: dotnet build NutrishaAI.API/NutrishaAI.API.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish NutrishaAI.API/NutrishaAI.API.csproj --configuration Release --no-build --output ./publish

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'risha'  # Replace with your Azure Web App name
        package: './publish'